name: cat_trivia
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #network
  retrofit: ^4.4.0
  dio: ^5.7.0

  #generators
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  #di
  get_it: ^8.0.2

  #animations:
  lottie: ^3.1.0


  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.5
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  freezed: ^2.5.7
  analyzer: ^6.7.0
  json_serializable: ^6.9.0


flutter:


  uses-material-design: true

  assets:
    - assets/




